import { defineConfig } from 'wxt';

export default defineConfig({
  manifestVersion: 3,
  modules: ['@wxt-dev/module-react'],
  manifest: {
    name: 'SyncNos-AI+Web Clipper',
    version: '1.1.0',
    description:
      'Clip AI chats to local storage, export to JSON or Markdown, and sync to Notion on demand.',
    permissions: [
      'storage',
      'tabs',
      'webNavigation',
      'activeTab',
      'scripting',
    ],
    host_permissions: [
      'https://chat.openai.com/*',
      'https://chatgpt.com/*',
      'https://www.chatgpt.com/*',
      'https://claude.ai/*',
      'https://gemini.google.com/*',
      'https://chat.deepseek.com/*',
      'https://chat.z.ai/*',
      'https://kimi.moonshot.cn/*',
      'https://kimi.com/*',
      'https://*.kimi.com/*',
      'https://www.doubao.com/*',
      'https://yuanbao.tencent.com/*',
      'https://poe.com/*',
      'https://*.notion.so/*',
      'https://*.notionusercontent.com/*',
      'https://img.notionusercontent.com/*',
      'https://api.notion.com/*',
      'https://syncnos-notion-oauth.chiimagnus.workers.dev/*',
      'https://chiimagnus.github.io/*',
      'http://*/*',
      'https://*/*',
    ],
    web_accessible_resources: [
      {
        resources: ['icons/icon-128.png'],
        matches: [
          'https://chat.openai.com/*',
          'https://chatgpt.com/*',
          'https://www.chatgpt.com/*',
          'https://claude.ai/*',
          'https://gemini.google.com/*',
          'https://chat.deepseek.com/*',
          'https://chat.z.ai/*',
          'https://kimi.moonshot.cn/*',
          'https://kimi.com/*',
          'https://*.kimi.com/*',
          'https://www.doubao.com/*',
          'https://yuanbao.tencent.com/*',
          'https://poe.com/*',
          'https://*.notion.so/*',
          'http://*/*',
          'https://*/*',
        ],
      },
    ],
    icons: {
      16: 'icons/icon-16.png',
      48: 'icons/icon-48.png',
      128: 'icons/icon-128.png',
    },
  },
});
